"""initial migration

Revision ID: 93e0ca78213e
Revises: 
Create Date: 2023-09-20 15:52:28.013903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e0ca78213e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers'))
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_products_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_manufacturer_id'), 'products', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_index(op.f('ix_products_year'), 'products', ['year'], unique=False)
    op.create_table('orders_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orders_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_items_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name=op.f('pk_orders_items'))
    )
    op.create_table('products_countries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_products_countries_country_id_countries')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_countries_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'country_id', name=op.f('pk_products_countries'))
    )
    op.create_table('products_reviews',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_products_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'customer_id', name=op.f('pk_products_reviews'))
    )
    op.create_index(op.f('ix_products_reviews_timestamp'), 'products_reviews', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_reviews_timestamp'), table_name='products_reviews')
    op.drop_table('products_reviews')
    op.drop_table('products_countries')
    op.drop_table('orders_items')
    op.drop_index(op.f('ix_products_year'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_manufacturer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
